// generated by stringer -type=Type; DO NOT EDIT

package scan

import "fmt"

const _Type_name = "EOFErrorNewlineFuncAssignCharIdentifierNumberOpRationalLeftParenRightParenSemicolonString"

var _Type_index = [...]uint8{0, 3, 8, 15, 19, 25, 29, 39, 45, 47, 55, 64, 74, 83, 89}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
